### ISSUE TITLE
i can't open chinese doc site

### ISSUE THREAD

**Issue by flynn-eye** [moleculerjs/site#146]
https://moleculer.services/zh/

**Comment by intech** [comment]
@flynn-eye Thanks for reporting the issue!
Temporarily you can use the [link](https://moleculer.services/zh/docs/0.14/index.html)

**Comment by icebob** [comment]
The issue is that that `layout` meta value is translated:
![image](https://user-images.githubusercontent.com/306521/121800226-e35dbd80-cc30-11eb-82ae-f8a554aeac3c.png)

I'm fixing.
