### ISSUE TITLE
Retry topic in Fault tolerance needs to be a bit clearer

### ISSUE THREAD

**Issue by henriquesml** [moleculerjs/site#188]
Hello guys,

I noticed in the [Retry documentation](https://moleculer.services/docs/0.14/fault-tolerance.html#Retry) needs a complementation. To retry a failed request, the action needs to `throw` a `MoleculerRetryableError` rigth?. I think that return type needs to be informed in this section, with a ref to [Erros page](https://moleculer.services/docs/0.14/errors.html#MoleculerRetryableError) maybe.

Thank you, Molecule is a awesome project!

**Comment by intech** [comment]
@henriquesml Thanks! Fix in https://github.com/moleculerjs/site/commit/3ef4b12140053907b70966f72053f3f8e316d7f1
