### ISSUE TITLE
Clarification on "Avoid deadlocks"

### ISSUE THREAD

**Issue by GHNewbiee** [moleculerjs/site#32]
Hi,

In **Avoid deadlocks** note of **Lifecycle.md** it is referred:

> ... To avoid it, remove the concerned service from dependencies and use `this.waitForServices` method out of `started` handler instead.

"the concerned service" means any one of the two services. Correct?

I cannot understand what "out of `started` handler instead." means. Especially the "out of"! Please, make it clearer, if possible or give an example.

Tia

**Comment by icebob** [comment]
Fixed to _To avoid it, remove the concerned service from dependencies and use `this.waitForServices` method in `started` handler instead_.
