### ISSUE TITLE
Broker, Service and Middleware Semantic suggestion

### ISSUE THREAD

**Issue by GHNewbiee** [moleculerjs/site#34]
Hi,

Please, next find my suggestion.

Broker
------
| Option A | Option B |
|----|----|
|broker.start()  (reflexive)| broker.start()|
|broker.stop()  (reflexive)| broker.stop()|
|broker.startREPL() | broker.repl()|
|broker.getError() | broker.error()|
|broker.getLogger() | broker.logger()|
|broker.loadService() | broker.load()|
|broker.loadServices() | broker.mload()|
|broker.createService() | broker.create()|
|broker.destroyService() | broker.destroy()|
|broker.getLocalService() | broker.local()|
|broker.waitForServices() | broker.wait()|
|broker.callService() | broker.call()|
|broker.callServices() | broker.mcall()|
|broker.emitEvent() | broker.emit()|
|broker.broadcastEvent()| broker.broadcast()|
|broker.broadcastEventLocal() | broker.broadcastLocal()|
|broker.pingNode() | broker.ping()|
|afterCreate() (reflexive) | created()|
|afterStart() (reflexive)  | started()|
|beforeStop() (reflexive)  | stopping()|

Service
-------
|Option A | Option B|
|----|----|
|aftercreated() (reflexive) | created()|
|beforeBrokerStart()        | brokerStarting()|
|beforeBrokerStop()         | brokerStopping()|

Middleware
----------
|Option A | Option B|
|----|----|
|callService() | call()|
|callServices() | mcall()|
|emitEvent() | emit()|
|broadcastEvent() | broadcast()|
|broadcastEventLocal() | broadcastLocal()|
|afterServiceCreate() | serviceCreated()|
|beforeServiceStart() | serviceStarting()|
|afterServiceStart()  | serviceStarted()|
|beforeServiceStop()  | serviceStopping()|
|afterServiceStop()   | serviceStopped()|
|afterBrokerCreate()  | brokerCreated()|
|beforeBrokerStart()  | brokerStarting()|
|afterBrokerStart()   | brokerStarted()|
|beforeBrokerStop()   | brokerStopping()|
|afterBrokerStop()    | brokerStopped()|

Tia

**Comment by icebob** [comment]
Sorry, but no way that I rename the whole framework methods.

**Comment by GHNewbiee** [comment]
I understand that very well! Although, imho when something is not absolutely precise, the best time to improve it is as soon as possible, because in long term you will face it and then it will get more and more painful to improve it. More projects will be broken and more future developers (hopefully) will start complaining about that!

In the simplest case, imagine that one clones the project, devotes some time to improve the semantics so they are easily understandable, remove any ambiguity about (preposition-noun-verb) timing and update the documentation, and finally establishes a new project called, let's say, "MicroSimplyServices". Which project a future developer will choose to work with? This is an imaginary case.

So, if you also believe that there is still room for improvement to the semantics, please think it again.

Tia
