### ISSUE TITLE
Ask Netlify to switch shared IP for moleculer.services.

### ISSUE THREAD

**Issue by fugufish** [moleculerjs/site#59]
I am a lead engineer and architect at Morgan Stanley, the fourth largest investment bank in the world. I have for some time been working on a project that unifies many of our systems communicate with each other, using moleculer as the service bus.

From my understanding the site is hosted on netlify, and currently moleculer.services shared ip is `104.198.14.52`. Unfortunately this IP has been blacklisted due hosting other sites with malicious content

https://www.virustotal.com/en/ip-address/104.198.14.52/information/

I will be presenting my proposal in the next month, but it will be hard as our firewall actively blocks moleculer.services due to the IP address being blacklisted. Would it be possible to ask netlify to move your instance to an IP that doesn't.. for the lack of a better word, suck?

**Comment by icebob** [comment]
I don't think, that we can find other IP addresses at where there is no other blacklisted site.

Try to use https://moleculer.netlify.com or https://moleculerjs.com

**Comment by fugufish** [comment]
they all use the same IP. as for finding other IP addresses, I can get to many other netlify hosted sites just fine, so far its just this one that I have encountered the issue with.

**Comment by icebob** [comment]
The moleculer.netlify.com points to 167.99.137.12, doesn't it?

**Comment by fugufish** [comment]
ping moleculer.netlify.com
PING moleculer.netlify.com (104.248.78.23): 56 data bytes
64 bytes from 104.248.78.23: icmp_seq=0 ttl=53 time=96.470 ms
64 bytes from 104.248.78.23: icmp_seq=1 ttl=53 time=90.640 ms


Is what I get

**Comment by icebob** [comment]
Interesting. It's for me:

```
d:\>ping moleculer.netlify.com

Pinging moleculer.netlify.com [167.99.137.12] with 32 bytes of data:
Reply from 167.99.137.12: bytes=32 time=50ms TTL=59
Reply from 167.99.137.12: bytes=32 time=49ms TTL=59
Reply from 167.99.137.12: bytes=32 time=51ms TTL=59
Reply from 167.99.137.12: bytes=32 time=49ms TTL=59

Ping statistics for 167.99.137.12:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 49ms, Maximum = 51ms, Average = 49ms
```

**Comment by icebob** [comment]
From [Netlify docs](https://www.netlify.com/docs/custom-domains/#dns-configuration): 
>Create an A record pointing your root domain to our load balancer’s IP address 104.198.14.52.

**Comment by icebob** [comment]
@fugufish try again. Now it points to 142.93.108.123

**Comment by fugufish** [comment]
Molecular.netlify.com now works, the other two are still blacklisted. I think I can get away with referencing the netlify subdomain for now though.

**Comment by icebob** [comment]
The moleculer.services points to moleculer.netlify.com, maybe try to flush dns cache.
