### ISSUE TITLE
To help the Russian community to have 100% access to the site

### ISSUE THREAD

**Issue by intech** [moleculerjs/site#67]
Hello @icebob !
In the Russian community constantly complain about the inaccessibility of the site due to the blocked ip address 167.99.137.12 of netlify.com hosting which uses its international CDN network.
To help the Russian community to have 100% access to the site, I provided Russian CDN hosting based on the largest site in Russia, Selectel (it hosts the largest social network in Russia, vk.com) for accessibility of the site throughout Russia without any restrictions. This CDN will never fall into restrictions and blocking.
Please indicate for subdomain ru.moleculer.services CNAME f906b9f8-f416-4d38-8970-9682515101cf.selcdn.net so that I can give a mirror for the Russian community!

**Comment by intech** [comment]
I went the other way :) I registered a domain, made a mirror moleculerjs.ru and automatically deployed from the repository to the selectel data center

**Comment by icebob** [comment]
@intech Ohh, it's great, thank you for your solution!
