### ISSUE TITLE
multi-language support

### ISSUE THREAD

**Issue by intech** [moleculerjs/site#68]
Hello, @icebob!
Help me with hexo, make an example with the support of another language, so that we can make a translation of the site and documentation into the main repository.
I have not previously worked with him and something I can not generate the correct site in working paths.

**Comment by intech** [comment]
I honestly tried to do with this instruction https://hexo.io/docs/internationalization but half of the site starts to prescribe the path /ru/ and in fact does not generate files with this path

**Comment by icebob** [comment]
Hi @intech ,
Ok, I will try to add an example lang in the repo.

**Comment by icebob** [comment]
I've checked Hexo. It has some support for multiple languages, but not very well. [Other libs](https://github.com/vuejs/vuejs.org#on-translations) use separated repos for other languages instead of one repo with multiple languages.
