### ISSUE TITLE
Headings on index page are linked to undefined

### ISSUE THREAD

**Issue by shindakun** [moleculerjs/site#98]
![Capture](https://user-images.githubusercontent.com/319128/78094793-434ca900-738a-11ea-9d2c-b3d24cab03c7.PNG)

I was checking out the site and I happened to notice an issue with the links on the main page. Decided to try and track it down and it looks like helpers.js isn't checking to see if headers have `id`.

https://github.com/moleculerjs/site/blob/121b604c6713950665089682bad3d4c1d243937e/scripts/helpers.js#L210-L212

Figured I may as well open an issue/PR.

**Comment by icebob** [comment]
Cool, thank you! I've merged your PR.
